config/routes.rb
Rails.application.routes.draw do
  get 'settings/consent'

  get 'settings/privacy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Searchjoy::Engine, at: "/admin/searchjoy"
  get 'welcome/index'
  get 'signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'signup_employer' => 'welcome#signup_employer'
  get 'welcome/signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'welcome/signup_employer' => 'welcome#signup_employer'

  get 'consent/business_consent/:id' => 'consent#business_consent', as: :business_consent
  get 'consent/adult_consent/:id' => 'consent#adult_consent', as: :adult_consent
  post 'consent/create' => 'consent#create'
  patch 'consent/update/:id' => 'consent#update'

  get 'search' => 'searches#index'
  get 'search/:id' => 'searches#navigate', as: :search_nav

  patch 'resource_links/all_announcements' => 'resource_links#update_all_announcements', as: :update_all_announcements
  patch 'resource_links/all_resource_links' => 'resource_links#update_all_resource_links', as: :update_all_resource_links

  get 'analytics' => 'analytics#index'
  get 'analytics/:id' => 'analytics#show', as: :analytics_report

  get 'notifications' => 'notifications#index'
  get 'notifications/show' => 'notifications#show', as: :show_notifications
  get 'notifications/:id' => 'notifications#trackable', as: :show_trackable
  patch 'notifications' => 'notifications#update'
  patch 'notifications/all' => 'notifications#update_all', as: :update_all_notifications
  delete 'notifications' => 'notifications#delete'
  delete 'notifications/all' => 'notifications#delete_all', as: :delete_all_notifications
  get 'users/referenceTab' => 'users#reference_tab'

  devise_for :users, controllers: { passwords: "users/passwords", sessions: "users/sessions", :registrations => "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  post 'users/home_tab' => 'users#home_tab'
  post 'users/nav_tab' => 'users#nav_tab'

  get '/users/:id/crop' => 'users#crop'
  get '/users/:id' => 'users#show', as: :user
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update'
  get 'users/:id/contact' => 'users#contact', as: :contact_user
  post 'users/:id/contact' => 'users#send_mail', as: :email_user

  patch 'skills/:id' => 'skills#update'
  post 'skills' => 'skills#create'
  get 'skills/autocomplete' => 'skills#autocomplete'

  get '/user_skills/:id/edit' => 'user_skills#edit', as: :edit_user_skill
  get '/user_skills/edit_all' => 'user_skills#edit_all', as: :edit_all_user_skill
  patch '/user_skills/update_all' => 'user_skills#update_all', as: :update_all_user_skill
  patch '/user_skills/:id' => 'user_skills#update'
  delete '/user_skills/:id' => 'user_skills#destroy', as: :delete_user_skill
  post '/user_skills' => 'user_skills#create'

  get 'job_postings' => 'job_postings#index'
  get 'job_postings/new' => 'job_postings#new', as: :new_job_posting
  get 'job_postings/refresh' => 'job_postings#refresh', as: :refresh_job_posting
  post 'job_postings/refresh' => 'job_postings#refresh_process', as: :refresh_job_posting_process
  get 'job_postings/:id' => 'job_postings#show', as: :job_posting
  get 'job_postings/:id/edit' => 'job_postings#edit', as: :edit_job_posting
  patch 'job_postings/:id' => 'job_postings#update'
  delete 'job_postings/:id' => 'job_postings#destroy'
  post 'job_postings' => 'job_postings#create'
  get 'job_postings/:id/compare' => 'job_postings#compare', as: :compare_applications

  get 'job_posting_applications/new' => 'job_posting_applications#new', as: :new_job_posting_application
  get 'job_posting_application/:id' => 'job_posting_applications#show', as: :job_posting_application
  post 'job_posting_applications' => 'job_posting_applications#create'
  patch 'job_posting_applications/:id' => 'job_posting_applications#update', as: :update_job_posting_application
  delete 'job_posting_application/:id' => 'job_posting_applications#destroy'

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/:id' => 'projects#show', as: :project
  get 'projects/:id/edit' => 'projects#edit', as: :edit_project
  patch 'projects/:id' => 'projects#update'
  post 'projects' => 'projects#create'
  delete 'projects/:id' => 'projects#destroy', as: :delete_project

  patch 'project_skills/:id' => 'project_skills#update'
  post 'project_skills' => 'project_skills#create'

  get 'references/refer' => 'references#email', as: :email_reference
  get 'references/new/:id' => 'references#new', as: :new_reference
  post 'references/refer' => 'references#send_mail', as: :reference_emails
  post 'references' => 'references#create'
  patch 'references/:id' => 'references#update', as: :update_reference
  delete 'references/:id' => 'references#destroy', as: :delete_reference

  delete 'reference_redirections/:id' => 'reference_redirections#destroy', as: :delete_reference_redirection

  get 'surveys/:title/compare' => 'surveys#compare', as: :compare_survey
  get 'surveys/:title/compare_to' => 'surveys#compare_to', as: :survey_compare_to
  get 'surveys/compare_all' => 'surveys#compare_all', as: :survey_compare_all
  get 'surveys' => 'surveys#index'
  get 'surveys/:title' => 'surveys#show', as: :survey
  get 'surveys/:title/edit' => 'surveys#edit', as: :edit_survey
  post 'responses' => 'responses#create'
  patch 'responses' => 'responses#update'

  get 'about_us' => 'welcome#about_us', as: :about_us
  get 'lost_email' => 'welcome#lost_email', as: :lost_email
  post 'lost_email' => 'welcome#send_lost_email', as: :send_lost_email
  get 'contact_us' => 'welcome#contact_us', as: :contact_us
  post 'contact_us' => 'welcome#send_contact_us', as: :send_contact_us
  root 'welcome#index'

  get '*path' => redirect('/')

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.nil?
          flash[:danger] = "We could not find this "+"#{provider}".capitalize+" account associated with a user account.  Please either make a new account or login with your main account, and then associate a "+"#{provider}".capitalize+" account with yours, in Edit Profile, Social Media tab."
          redirect_to root_path
        elsif @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to root_path
        end
      end
    }
  end

  [:facebook, :twitter, :github, :linkedin].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_filter :logged_in, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    if params[:role] == 'employee'
      @user.add_role :employee
    elsif params[:role] =='employer'
      @user.add_role :employer
    else
    end
    if verify_recaptcha(model: User.new)
      ##Extra.  To remove once consent/study is done
      if consent_name_match
        resource.save
        yield resource if block_given?
        if resource.persisted?
          resource.create_consent(consent_params)
          if resource.active_for_authentication?
            set_flash_message! :notice, :signed_up
            sign_up(resource_name, resource)
            respond_with resource, location: after_sign_up_path_for(resource)
          else
            set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}."
            expire_data_after_sign_in!
            respond_with resource, location: after_inactive_sign_up_path_for(resource)
          end
        else
          if params[:role] == 'employee'
            clean_up_passwords resource
            set_minimum_password_length
            @job_seeker = @user
            @job_seeker.build_consent(consent_params)
            render template: "welcome/signup_jobseeker" and return
          elsif params[:role] =='employer'
            clean_up_passwords resource
            set_minimum_password_length
            @employer = @user
            @employer.build_consent(consent_params)
            render template: "welcome/signup_employer" and return
          else
            flash[:danger] = "There was an error.  Please try again later, or contact an administrator."
            redirect_to root_path
          end
        end
      else
        if params[:role] == 'employee'
          clean_up_passwords resource
          set_minimum_password_length
          @job_seeker = @user
          @job_seeker.build_consent(consent_params)
          render template: "welcome/signup_jobseeker" and return
        elsif params[:role] =='employer'
          clean_up_passwords resource
          set_minimum_password_length
          @employer = @user
          @employer.build_consent(consent_params)
          render template: "welcome/signup_employer" and return
        else
          flash[:danger] = "There was an error.  Please try again later, or contact an administrator."
          redirect_to root_path
        end
      end
    else
      flash.now[:warning] = "Please redo the Captcha"
      if params[:role] == 'employee'
        @job_seeker = @user
        @job_seeker.build_consent(consent_params)
        render template: "welcome/signup_jobseeker" and return
      elsif params[:role] =='employer'
        @employer = @user
        @employer.build_consent(consent_params)
        render template: "welcome/signup_employer" and return
      else
        flash[:danger] = "There was an error.  Please try again later, or contact an administrator."
        redirect_to root_path
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def consent_name_match
    if params[:user].key?(:consent_attributes)
      unless (params[:user][:first_name].titleize+ " " + params[:user][:last_name].titleize).eql? params[:user][:consent_attributes][:name].titleize 
        flash.now[:warning] = "The name in the consent form must match the first and last name supplied."
        return false 
      end
    end
    return true
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :first_name, :last_name, :company_name, :postal_code, :city, :province, :gender, :birth_date])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end

  private
  def logged_in
    if user_signed_in?
      redirect_to root_path
    end
  end

  def consent_params
      params.require(:user).require(:consent_attributes).permit(:user_id, :name, :date_signed, :answer, :consent_type)
    end
  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper

	def link_to_add_announcement_fields(name, f, css_class = "")
     	new_object = ResourceLink.new
     	association = :resource_links
    	fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
       		render("/users/announcement_fields", id: "new_#{association}", f: builder)
     	end
     	link_to name, 'javascript:;', onclick: "add_announcement_fields(\"#{association}\", \"#{escape_javascript(fields)}\")", class: css_class
   	end

   	def link_to_add_resource_link_fields(name, f, css_class = "")
     	new_object = ResourceLink.new
     	association = :resource_links
    	fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
       		render("/users/resource_link_fields", id: "new_#{association}", f: builder)
     	end
     	link_to name, 'javascript:;', onclick: "add_resource_link_fields(\"#{association}\", \"#{escape_javascript(fields)}\")", class: css_class
   	end
end

app/views/users/shared/_employer_home_tabs.html.erb
<div class="container" id="profileButtons">
   <ul class="nav nav-tabs profileButtonContent">
      <% if user_signed_in? && @current_user==@user %>
      	<% if session[:home_tab] == "jobs" %>
            <li onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setHomeTab("about");><a data-toggle="tab" href="#about">ABOUT US</a></li> 
            <li class="active" onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setHomeTab("jobs");><a data-toggle="tab" href="#jobs">JOBS</a></li>
         <% else %>
            <li class="active" onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setHomeTab("about");><a data-toggle="tab" href="#about">ABOUT US</a></li> 
            <li onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setHomeTab("jobs");><a data-toggle="tab" href="#jobs">JOBS</a></li>
         <% end %>
      <% else %>
         <% if session[:nav_tab] == "jobs" %>
            <li onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setNavTab("about");><a data-toggle="tab" href="#about">ABOUT US</a></li> 
            <li class="active" onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setNavTab("jobs");><a data-toggle="tab" href="#jobs">JOBS</a></li>
      	<% else %>
      		<li class="active" onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setNavTab("about");><a data-toggle="tab" href="#about">ABOUT US</a></li> 
      		<li onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onmousedown=setNavTab("jobs");><a data-toggle="tab" href="#jobs">JOBS</a></li>
      	<% end %>
      <% end %>
   </ul>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' && controller_name != 'welcome' && controller_name != 'registrations' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' && controller_name != 'sessions' && controller_name != 'welcome' %>
  <%= link_to "Sign up", welcome_index_path %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' && controller_name != 'welcome' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'registrations' && controller_name != 'welcome' %>
<%= link_to "Forgot your email?", lost_email_path %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <!--<%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(resource_name) %><br /> -->
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/users/shared/_profile.html.erb
<% if @user.has_role? :employee %>
<!-- Employee Profile -->
	<div class ="profileContainer row">
		<div class ="profileContainerImage">
			<% if @user.formatted_picture(current_user) %>
				<% if defined? edit %>
					<div class="profile-image fix-display medium-shadow">
						<%= image_tag @user.image.url(:medium), alt:"User Icon", id: "profile" %>
					</div>
				<% else %>
					<div class="profile-image medium-shadow">
						<%= image_tag @user.image.url(:medium), alt:"User Icon" %>
					</div>
				<% end %>
			<% elsif @user.gender == "male" %>
				<%= image_tag "avatar-placeholderM-medium.svg", alt: "User Icon", class: "profile-image medium-shadow" %>
			<% elsif @user.gender == "female" %>
				<%= image_tag "avatar-placeholderF-medium.svg", alt: "User Icon", class: "profile-image medium-shadow" %>
			<% else %>
				<%= image_tag "avatar-placeholder-medium.svg", alt: "User Icon", class: "profile-image medium-shadow" %>
			<% end %>
		</div>
		<%if @user == current_user %>
		<div class ="profileContainerContent col-xs-9 col-sm-8 col-md-4">
		<% else %>
		<div class ="profileContainerContent col-xs-9 col-sm-8 col-md-8">
		<% end %>
			<h2> <%= link_to @user.formatted_name(current_user), @user %> </h2>
	
			<h5> <%= @user.formatted_job(current_user) %></h5>

			<h5><%= @user.formatted_location(current_user) %></h5>

			<h5>
				<% if !@user.github.nil? %>
					<%= link_to 'GitHub', @user.github, id: 'github', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %>
				<% end %>
				<% if !@user.linkedin.nil? %>
					<%= link_to 'Linkedin', @user.linkedin, id: 'linkedin', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
				<% if !@user.twitter.nil? %>
					<%= link_to 'Twitter', @user.twitter, id: 'twitter', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
				<% if !@user.facebook.nil? %>
					<%= link_to 'Facebook', @user.facebook, id: 'facebook', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
			</h5>
			<h5><%= @user.summary %></h5>
			<% if user_signed_in? && current_user.has_role?(:employer) %>
				<div style="margin-top:10px;">
					<%= link_to 'Contact '+@user.formatted_name(current_user), contact_user_path(@user), class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
		<% if user_signed_in? && @user == current_user %>
			<div class="bulletin-board col-xs-12 col-sm-12 col-md-5">
				<ul>
					<%= render 'shared/user_buckets' %>
				</ul>
			</div>
		<% end %>
	</div>
<% elsif @user.has_role? :employer %>
<!-- Employer Profile -->
	<div class ="profileContainer row">
		<div class ="profileContainerImage">
			<% if defined? edit %>
				<div class="profile-image fix-display medium-shadow">
					<%= image_tag @user.image.url(:medium), alt:"User Icon", id: "profile" %>
				</div>
			<% else %>
				<div class="profile-image medium-shadow">
					<%= image_tag @user.image.url(:medium), alt:"User Icon" %>
				</div>
			<% end %>
		</div>
		<%if @user == current_user %>
		<div class ="profileContainerContent col-xs-9 col-sm-8 col-md-4">
		<% else %>
		<div class ="profileContainerContent col-xs-9 col-sm-8 col-md-8">
		<% end %>
			<h2> <%= link_to @user.company_name, @user %></h2>
			<h5> <%= @user.street_address %><br><%= @user.city %> <%= @user.province %> <%= @user.postal_code %> </h5>
			<h5> <%= @user.email %> </h5>
			<h5>
				<% if !@user.linkedin.nil? %>
					<%= link_to 'Linkedin', @user.linkedin, id: 'linkedin', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
				<% if !@user.twitter.nil? %>
					<%= link_to 'Twitter', @user.twitter, id: 'twitter', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
				<% if !@user.facebook.nil? %>
					<%= link_to 'Facebook', @user.facebook, id: 'facebook', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
			</h5>
			<h5><%= @user.summary %></h5>
		</div>
		<% if user_signed_in? && @user == current_user %>
			<div class="bulletin-board col-xs-12 col-sm-12 col-md-5 pull-right">
				<ul>
					<%= render 'shared/user_buckets' %>
				</ul>
			</div>
		<% end %>
	</div>
<% else %>
	<!-- admin -->
	<div class ="profileContainer row">
		<div class ="profileContainerImage">
			<% if defined? edit %>
				<div class="profile-image fix-display medium-shadow">
					<%= image_tag @user.image.url(:medium), alt:"User Icon", id: "profile" %>
				</div>
			<% else %>
				<div class="profile-image medium-shadow">
					<%= image_tag @user.image.url(:medium), alt:"User Icon" %>
				</div>
			<% end %>
		</div>
		<%if @user == current_user %>
		<div class ="profileContainerContent col-xs-9 col-sm-8 col-md-4">
		<% else %>
		<div class ="profileContainerContent col-xs-9 col-sm-8 col-md-8">
		<% end %>
			<h2> <%= link_to "Admin", @user %></h2>
			
			<h5>
				<% if !@user.linkedin.nil? %>
					<%= link_to 'Linkedin', @user.linkedin, id: 'linkedin', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
				<% if !@user.twitter.nil? %>
					<%= link_to 'Twitter', @user.twitter, id: 'twitter', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
				<% if !@user.facebook.nil? %>
					<%= link_to 'Facebook', @user.facebook, id: 'facebook', onmouseover: 'buttonOpac(this)', onmouseout:'buttonRevOpac(this)' %> 
				<% end %>
			</h5>
			<h5><%= @user.summary %></h5>
		</div>
		<% if user_signed_in? && @user == current_user %>
			<div class="bulletin-board col-xs-12 col-sm-12 col-md-5 pull-right">
				<ul>
					<%= render 'shared/user_buckets' %>
				</ul>
			</div>
		<% end %>
	</div>
<% end %>