config/routes.rb
Rails.application.routes.draw do
  get 'settings/consent'

  get 'settings/privacy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Searchjoy::Engine, at: "/admin/searchjoy"
  get 'welcome/index'
  get 'signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'signup_employer' => 'welcome#signup_employer'
  get 'welcome/signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'welcome/signup_employer' => 'welcome#signup_employer'

  get 'consent/business_consent/:id' => 'consent#business_consent', as: :business_consent
  get 'consent/adult_consent/:id' => 'consent#adult_consent', as: :adult_consent
  post 'consent/create' => 'consent#create'
  patch 'consent/update/:id' => 'consent#update'

  get 'search' => 'searches#index'
  get 'search/:id' => 'searches#navigate', as: :search_nav

  patch 'resource_links/all_announcements' => 'resource_links#update_all_announcements', as: :update_all_announcements
  patch 'resource_links/all_resource_links' => 'resource_links#update_all_resource_links', as: :update_all_resource_links

  get 'analytics' => 'analytics#index'
  get 'analytics/:id' => 'analytics#show', as: :analytics_report

  get 'notifications' => 'notifications#index'
  get 'notifications/show' => 'notifications#show', as: :show_notifications
  get 'notifications/:id' => 'notifications#trackable', as: :show_trackable
  patch 'notifications' => 'notifications#update'
  patch 'notifications/all' => 'notifications#update_all', as: :update_all_notifications
  delete 'notifications' => 'notifications#delete'
  delete 'notifications/all' => 'notifications#delete_all', as: :delete_all_notifications
  get 'users/referenceTab' => 'users#reference_tab'

  devise_for :users, controllers: { passwords: "users/passwords", sessions: "users/sessions", :registrations => "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  post 'users/home_tab' => 'users#home_tab'
  post 'users/nav_tab' => 'users#nav_tab'

  get '/users/:id/crop' => 'users#crop'
  get '/users/:id' => 'users#show', as: :user
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update'
  get 'users/:id/contact' => 'users#contact', as: :contact_user
  post 'users/:id/contact' => 'users#send_mail', as: :email_user

  patch 'skills/:id' => 'skills#update'
  post 'skills' => 'skills#create'
  get 'skills/autocomplete' => 'skills#autocomplete'

  get '/user_skills/:id/edit' => 'user_skills#edit', as: :edit_user_skill
  get '/user_skills/edit_all' => 'user_skills#edit_all', as: :edit_all_user_skill
  patch '/user_skills/update_all' => 'user_skills#update_all', as: :update_all_user_skill
  patch '/user_skills/:id' => 'user_skills#update'
  delete '/user_skills/:id' => 'user_skills#destroy', as: :delete_user_skill
  post '/user_skills' => 'user_skills#create'

  get 'job_postings' => 'job_postings#index'
  get 'job_postings/new' => 'job_postings#new', as: :new_job_posting
  get 'job_postings/refresh' => 'job_postings#refresh', as: :refresh_job_posting
  post 'job_postings/refresh' => 'job_postings#refresh_process', as: :refresh_job_posting_process
  get 'job_postings/:id' => 'job_postings#show', as: :job_posting
  get 'job_postings/:id/edit' => 'job_postings#edit', as: :edit_job_posting
  patch 'job_postings/:id' => 'job_postings#update'
  delete 'job_postings/:id' => 'job_postings#destroy'
  post 'job_postings' => 'job_postings#create'
  get 'job_postings/:id/compare' => 'job_postings#compare', as: :compare_applications

  get 'job_posting_applications/new' => 'job_posting_applications#new', as: :new_job_posting_application
  get 'job_posting_application/:id' => 'job_posting_applications#show', as: :job_posting_application
  post 'job_posting_applications' => 'job_posting_applications#create'
  patch 'job_posting_applications/:id' => 'job_posting_applications#update', as: :update_job_posting_application
  delete 'job_posting_application/:id' => 'job_posting_applications#destroy'

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/:id' => 'projects#show', as: :project
  get 'projects/:id/edit' => 'projects#edit', as: :edit_project
  patch 'projects/:id' => 'projects#update'
  post 'projects' => 'projects#create'
  delete 'projects/:id' => 'projects#destroy', as: :delete_project

  patch 'project_skills/:id' => 'project_skills#update'
  post 'project_skills' => 'project_skills#create'

  get 'references/refer' => 'references#email', as: :email_reference
  get 'references/new/:id' => 'references#new', as: :new_reference
  post 'references/refer' => 'references#send_mail', as: :reference_emails
  post 'references' => 'references#create'
  patch 'references/:id' => 'references#update', as: :update_reference
  delete 'references/:id' => 'references#destroy', as: :delete_reference

  delete 'reference_redirections/:id' => 'reference_redirections#destroy', as: :delete_reference_redirection

  get 'surveys/:title/compare' => 'surveys#compare', as: :compare_survey
  get 'surveys/:title/compare_to' => 'surveys#compare_to', as: :survey_compare_to
  get 'surveys/compare_all' => 'surveys#compare_all', as: :survey_compare_all
  get 'surveys' => 'surveys#index'
  get 'surveys/:title' => 'surveys#show', as: :survey
  get 'surveys/:title/edit' => 'surveys#edit', as: :edit_survey
  post 'responses' => 'responses#create'
  patch 'responses' => 'responses#update'

  get 'about_us' => 'welcome#about_us', as: :about_us
  get 'lost_email' => 'welcome#lost_email', as: :lost_email
  post 'lost_email' => 'welcome#send_lost_email', as: :send_lost_email
  get 'contact_us' => 'welcome#contact_us', as: :contact_us
  post 'contact_us' => 'welcome#send_contact_us', as: :send_contact_us
  root 'welcome#index'

  get '*path' => redirect('/')

end

app/views/shared/_dismissable_alert.html.erb
<div class="alert alert-<%=type%> alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<p><%=msg%></p>
</div>

app/views/shared/_employer_tabs.html.erb
<div class="container" id="profileButtons">
   <ul class="nav nav-tabs profileButtonContent">

      <!-- include tab for employers to contact employees -->
      <% if @user.has_role? :employee %>

      <% elsif @user.has_role? :employer %>
         <!--
         ## Example
         render partial: "shared/employer_tabs", locals: { active: 'posting', job: @job_posting, user_path: user_path(@user) }
         ##User - Job Provider
            ##General/Common Tabs for All
               ##variable is user_path
               ##About Us
               ##Jobs
            ##Posting Tabs
               ##variable is posting_path 
               ##variable job is conditional for these tabs
               ##Applicants
               ##Survey/Ideal Candidate
               ##Posting Info
            ##New Posting Tab
              ## variable new_job is conditional for these tabs
         -->
         <!-- preprocess variables -->
         <% user_path = defined?(user_path) && !user_path.blank? ? ',"' + user_path + '"' : ''%>
         <% posting_path = defined?(posting_path) && !posting_path.blank? ? ',"' + posting_path + '"' : ''%>

         <!-- setup pre and post suffix -->
         <% pre = user_signed_in? && @current_user==@user ? "setHomeTab(" : "setNavTab(" %>
         <% post = ");" %>

         <!-- Setup class-active variables -->
         <% aboutClass = "" %>
         <% jobClass = "" %>
         <% surveyClass = "" %>
         <% postingClass = "" %>
         <% appClass = "" %>

         <% if active == "new_job" %>
            <!-- To ensure no other actives get through -->
         <% elsif active == "jobs" %>
            <% jobClass = "class=active" %>
         <% elsif active == "posting" && defined?(job) %>
            <% postingClass = "class=active" %>
         <% elsif active == "survey" && defined?(job)  %>
            <% surveyClass = "class=active" %>
         <% elsif active == "applicants" && defined?(job) %>
            <% appClass = "class=active" %>
         <% else %>
            <% aboutClass = "class=active" %>
         <% end %>

         <!-- Display Tabs -->
         <% if active == "new_job" %>
            <li class="active" onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this);>
               <a data-toggle="tab" href="#">NEW JOB POSTING</a>
            </li>
         <% end %>
         <% if defined?(job) %>
            <% if current_user == @user && current_user == job.user %>
               <li <%= appClass %> onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onclick=<%= pre+"\'applicants\'"+posting_path+post%>>
                  <a data-toggle="tab" href="#applicants">APPLICANTS</a>
               </li>
            <% end %>
            <li <%= surveyClass %> onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onclick=<%= pre+"\'survey\'"+posting_path+post%>>
               <a data-toggle="tab" href="#survey">IDEAL CANDIDATE</a>
            </li>
            <li <%= postingClass %> onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onclick=<%= pre+"\'posting\'"+posting_path+post%>>
               <a data-toggle="tab" href="#posting"><%= job.title.upcase %></a>
            </li>
         <% end %>
         <li <%= aboutClass %> onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onclick=<%= pre+"\'about\'"+user_path+post%>>
            <a data-toggle="tab" href="#about">ABOUT US</a>
         </li> 
         <li <%= jobClass %> onmouseover=buttonOpac(this); onmouseout=buttonRevOpac(this); onclick=<%= pre+"\'jobs\'"+user_path+post%>>
            <a data-toggle="tab" href="#jobs">JOBS</a>
         </li>
      <% end %>
   </ul>
</div>

app/views/shared/_footer.html.erb
<footer>
<div class="container" style="padding-right: -15px;">
	<center>
		<div class="footer-images">
			<%= image_tag "ubco.png", size: "33x45" %><!-- original dimensions are 99x135 -->
			<%= image_tag "wilfrid_laurier_seal.jpg", size: "50x50" %><!-- original dimensions are 301x300 -->
			<%= image_tag "brandon.png", size: "32x45" %><!-- original dimensions are 187x270 -->
			<%= image_tag "SSHRC-CRSH_FIP.jpg", size: "717x30" %><!-- original dimensions are 1507x63 -->
		</div>
	</center>
</div>
</footer>

app/views/shared/_message.html.erb
<% flash.each do |key, value| %>
	<% alert_class = case key
                   	when "notice" then "success"
                   	when "alert" then "danger"
                   	else key
                   	end %>
	<%= content_tag :div, class: "alert alert-#{alert_class}" do %>
		<% if key == "danger"%>
			<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
		<% end %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= value %>
	<% end %>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="glyphicon glyphicon-menu-hamburger" aria-label="Toggle navigation"></span>
      </button>
      <div class="login-menu">
        <%= link_to(image_tag("banner.svg", class: 'image-responsive', size: '92x40'), root_path, method: :get) %><!-- original size is 1000x434 -->
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbar">

      <%= form_tag "/search", method: "get", class: "nav navbar-nav navbar-form", role:"search", id: 'search' do %>
        <div class="input-group">
            <%= text_field_tag 'q', params[:q], class: 'round-border form-control', placeholder: "Search", autocomplete:"off", style: "width: 170px;" %>
            <%= hidden_field_tag 't', params[:t] %>
            <%= button_tag type: "submit", class: "btn btn-default margin-left-5", name: nil do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.has_role?(:admin) %>
          <li><%= link_to 'Admin', rails_admin_path %></li>
          <li><%= link_to 'Analytics', analytics_path %></li>
        <% end %>
        <li><a href='/search?utf8=✓&q=&t=JobPostings'>Job Postings</a></li>
        <li><%= link_to 'About Us', about_us_path %></li>
        <li><%= link_to 'Contact Us', contact_us_path %></li>

        <% if user_signed_in? %>
          <li class="dropdown">                                   
            <%= link_to show_notifications_path, html_options = 
            {class: "dropdown-toggle", "data-toggle"=>"dropdown","data-remote"=>"true"}, remote: true do %>
              <span class="glyphicon glyphicon-bell notifications-bell" aria-label="Notifications"></span>
              <span class = "notifications-counter" id="notif-num" style="<%=@notif_count_style%>" data-turbolinks-permanent><%= @notif_unseen %></span>
            <% end %>

            <ul class="dropdown-menu notif-bar" role="menu">
              <li id="notif-list" onscroll="checkNotificationScroll()">
                <img id="notif-loading" class="loading-image" src="<%=asset_path('loading.gif')%>" alt="Loading..">
              </li>
              <li><%= link_to "Show all notifications", notifications_path, class: "center-text" %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle padding-5" data-toggle="dropdown"><%= image_tag current_user.image.url(:menu), alt:"User Icon", class: "profile-image menu-shadow" %>Me<span class="caret"></span></a>
            <ul class="dropdown-menu padding-10" role="menu">
              <li class="menu-profile">
                <%= image_tag current_user.image.url(:thumb), alt:"User Icon", class: "profile-image menu-image thumb-shadow" %>
                <div class="menu-name">
                  <% if current_user.has_role?(:employee) %>
                    <%= (current_user.first_name+" "+current_user.last_name).truncate(20) %>
                  <% elsif current_user.has_role?(:employer) %>
                    <%= current_user.company_name %>
                  <% else %>
                    Admin
                  <% end %>
                  <br />
                  <%= link_to "View Profile", user_path(current_user) %>
                </div>
                <div style="clear:both;"></div>
              </li>
              <hr class="margin-all-10">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <!-- Placeholder: Will this be used? -->
              <li><%= link_to "Consent", '/settings/consent' %></li>
              <hr class="margin-all-10">
              <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <div class="login-menu">
              <%= link_to 'Login', new_user_session_path, class: "btn btn-info", style: 'color: #FFFFFF;' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notification.html.erb
<% options = get_read_options(activity)%>
<% notification_id = "notification-" +activity.id.to_s %>
<% if spacing %>
<li id="<%=notification_id%>" class="<%=options[0]%> alternate margin-top-5">
<% else %>
<li id="<%=notification_id%>" class="<%=options[0]%> alternate">
<% end %>
	<div class="notif-inside">
		<div class="content" onclick="window.location='<%=show_trackable_path(activity)%>'">
			<div style="display:flex;"><%= render_activity activity %></div>
		</div>
		<div class="controls">
			<div><%= link_to notifications_path(id: activity.id), remote: true, method: "delete" do %>
					<span class="glyphicon glyphicon-remove"></span>
			 	<% end %>
			</div>
			<div>
				<%= link_to notifications_path(id: activity.id), remote: true, method: "patch", style: "#{options[1]}" do %>
					<span class="glyphicon glyphicon-ok-circle"></span>
				<% end %>
			</div>
		</div>
		<div style="clear:both;"></div>
	</div>
</li>

app/views/shared/_notifications.html.erb
<% if !local_activities.empty? %>
	<% for activity in local_activities %>
		<% next if check_and_remove(activity) %>
		<% if defined?(spacing) && spacing %>
			<%= render '/shared/notification', activity: activity, spacing: true %>
		<% else %>
			<%= render '/shared/notification', activity: activity, spacing: false %>
		<% end %>
	<% end %>
<% else %>
	<li class="center-text"> You have no notifications! </li>
<% end %>

app/views/shared/_user_buckets.html.erb
<% if user_signed_in?  && current_user == @user %>
	<% if current_user.has_role? :employee %>
		<% @user_buckets.each_with_index do |bucket, index| %>
			<% if defined?(number_buckets) && index >= number_buckets %>
				<% break %>
			<% end %>
			<% case bucket[0] %>
			<% when :new_user_project %>
				<li style="margin: 10px 0px;">Need some help learning how to showcase your <%= link_to "projects?", bucket[1] %></li>
			<% when :new_user_survey %>
				<li style="margin: 10px 0px;">Need some help learning how to showcase your <%= link_to "skill surveys?", bucket[1] %></li>
			<% when :new_user_compare_other %>
				<li style="margin: 10px 0px;">Did you know, you can compare <%= link_to "yourself to other job seekers?", bucket[1] %></li>
			<% when :new_user_compare_job %>
				<li style="margin: 10px 0px;">Did you know, you can compare <%= link_to "yourself to an 'ideal candidate' of a job posting?", bucket[1] %></li>
			<% when :empty_survey %>
				<li style="margin: 10px 0px;">It seems you haven't answer all your <%= link_to "skill surveys", edit_survey_path(bucket[1]) %>.</li>
			<% when :old_survey %>
				<li style="margin: 10px 0px;">It can be helpful to <%= link_to "update", edit_survey_path(bucket[1]) %> your surveys once in a while.</li>
			<% when :user_skill %>
				<li style="margin: 10px 0px;">The most popular Job Seeker skill on EdgeMap is <%= bucket[1].titleize %>.</li>
			<% when :job_skill %>
				<li style="margin: 10px 0px;">The most sought after skill by Job Providers on EdgeMap is <%= bucket[1].titleize %>.</li>
			<% when :online %>
				<li style="margin: 10px 0px;"><%= I18n.t('users', count: bucket[1]) %> online right now.</li>
			<% when :unconfirmed %>
				<li style="margin: 10px 0px;">You have some unconfirmed references.  If everything checks out, <%= link_to "confirm", user_path(current_user), onclick: "setHomeTab('references')" %> them so Job Providers can learn more about you.</li>
			<% when :low_references %>
				<li style="margin: 10px 0px;">References are a great way for Job Providers to learn more about you, try <%= link_to "requesting some", email_reference_path %>.</li>
			<% else %>
				<li style="margin: 10px 0px;"><%= link_to bucket[0], bucket[1] %></li>
			<% end %>
		<% end %>
	<% elsif current_user.has_role? :employer %>
		<% @user_buckets.each_with_index do |bucket, index| %>
			<% if defined?(number_buckets) && index >= number_buckets %>
				<% break %>
			<% end %>
			<% case bucket[0] %>
			<% when :new_user_survey %>
				<li style="margin: 10px 0px;">Did you know, you can view a job seekers' skills in a <%= link_to "graph form, and find common language for what it means?", bucket[1] %></li>
			<% when :new_user_contact %>
				<li style="margin: 10px 0px;">Did you know, if you find an interesting job seeker, you can <%= link_to "contact them?", bucket[1] %></li>
			<% when :new_user_views %>
				<li style="margin: 10px 0px;">Did you know, you can see how many people <%= link_to "have viewed your job posting?", bucket[1] %></li>
			<% when :new_user_compare %>
				<li style="margin: 10px 0px;">Did you know, you can <%= link_to "compare applicants of a job in a graphical way?", bucket[1] %></li>
			<% when :new_user_search %>
				<li style="margin: 10px 0px;">Did you know, you can <%= link_to "search for job seekers based on their location?", bucket[1] %></li>
			<% when :bio %>
				<li style="margin: 10px 0px;">Your company biography is the first thing job seekers see on your page.  Include some info so they can know more about you.  Update it <%= link_to "here", user_path(current_user), onclick: "setHomeTab('bio')" %> </li>
			<% when :new_app %>
				<li style="margin: 10px 0px;">You have a new job posting applicant, you can view them <%= link_to 'here', '#', onclick: "window.location='"+show_trackable_path(bucket[1])+"'" %>.</li>
			<% when :user_skill %>
				<li style="margin: 10px 0px;">The most popular Job Seeker skill on EdgeMap is <%= bucket[1].titleize %>.</li>
			<% when :job_skill %>
				<li style="margin: 10px 0px;">The most sought after skill by Job Providers on EdgeMap is <%= bucket[1].titleize %>.</li>
			<% when :online %>
				<li style="margin: 10px 0px;"><%= I18n.t('users', count: bucket[1]) %> online right now.</li>
			<% when :expired_blank %>
				<li style="margin: 10px 0px;">You have a job posting that has expired and has no applicants.  You can extend it <%= link_to "here", edit_job_posting_path(bucket[1]) %></li>
			<% when :expired_with_apps %>
				<li style="margin: 10px 0px;">You have a job posting that has expired and has some applicants.  You can look at them <%= link_to 'here', '#', onclick: "setHomeTab(\'applicants\',\'"+job_posting_path(bucket[1])+"\');", data: { toggle: "tab" } %></li>
			<% else %>
				<li style="margin: 10px 0px;"><%= link_to bucket[0], bucket[1] %></li>
			<% end %>
		<% end %>
	<% else %>
		<% @user_buckets.each_with_index do |bucket, index| %>
			<% if defined?(number_buckets) && index >= number_buckets %>
				<% break %>
			<% end %>
			<% case bucket[0] %>
			<% when :user_skill %>
				<li style="margin: 10px 0px;">The most popular Job Seeker skill on EdgeMap is <%= bucket[1].titleize %>.</li>
			<% when :job_skill %>
				<li style="margin: 10px 0px;">The most sought after skill by Job Providers on EdgeMap is <%= bucket[1].titleize %>.</li>
			<% when :online %>
				<li style="margin: 10px 0px;"><%= I18n.t('users', count: bucket[1]) %> online right now.</li>
			<% else %>
				<li style="margin: 10px 0px;"><%= link_to bucket[0], bucket[1] %></li>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/shared/_user_summary.html.erb
<%= image_tag user.image.url(:small), class: "profile-image small-shadow" if !user.image.nil? %>

<h4> <%="#{user.first_name} #{user.last_name}"%></h4>
<%= link_to "View Profile", user_path(user)%>