config/routes.rb
Rails.application.routes.draw do
  get 'settings/consent'

  get 'settings/privacy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Searchjoy::Engine, at: "/admin/searchjoy"
  get 'welcome/index'
  get 'signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'signup_employer' => 'welcome#signup_employer'
  get 'welcome/signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'welcome/signup_employer' => 'welcome#signup_employer'

  get 'consent/business_consent/:id' => 'consent#business_consent', as: :business_consent
  get 'consent/adult_consent/:id' => 'consent#adult_consent', as: :adult_consent
  post 'consent/create' => 'consent#create'
  patch 'consent/update/:id' => 'consent#update'

  get 'search' => 'searches#index'
  get 'search/:id' => 'searches#navigate', as: :search_nav

  patch 'resource_links/all_announcements' => 'resource_links#update_all_announcements', as: :update_all_announcements
  patch 'resource_links/all_resource_links' => 'resource_links#update_all_resource_links', as: :update_all_resource_links

  get 'analytics' => 'analytics#index'
  get 'analytics/:id' => 'analytics#show', as: :analytics_report

  get 'notifications' => 'notifications#index'
  get 'notifications/show' => 'notifications#show', as: :show_notifications
  get 'notifications/:id' => 'notifications#trackable', as: :show_trackable
  patch 'notifications' => 'notifications#update'
  patch 'notifications/all' => 'notifications#update_all', as: :update_all_notifications
  delete 'notifications' => 'notifications#delete'
  delete 'notifications/all' => 'notifications#delete_all', as: :delete_all_notifications
  get 'users/referenceTab' => 'users#reference_tab'

  devise_for :users, controllers: { passwords: "users/passwords", sessions: "users/sessions", :registrations => "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  post 'users/home_tab' => 'users#home_tab'
  post 'users/nav_tab' => 'users#nav_tab'

  get '/users/:id/crop' => 'users#crop'
  get '/users/:id' => 'users#show', as: :user
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update'
  get 'users/:id/contact' => 'users#contact', as: :contact_user
  post 'users/:id/contact' => 'users#send_mail', as: :email_user

  patch 'skills/:id' => 'skills#update'
  post 'skills' => 'skills#create'
  get 'skills/autocomplete' => 'skills#autocomplete'

  get '/user_skills/:id/edit' => 'user_skills#edit', as: :edit_user_skill
  get '/user_skills/edit_all' => 'user_skills#edit_all', as: :edit_all_user_skill
  patch '/user_skills/update_all' => 'user_skills#update_all', as: :update_all_user_skill
  patch '/user_skills/:id' => 'user_skills#update'
  delete '/user_skills/:id' => 'user_skills#destroy', as: :delete_user_skill
  post '/user_skills' => 'user_skills#create'

  get 'job_postings' => 'job_postings#index'
  get 'job_postings/new' => 'job_postings#new', as: :new_job_posting
  get 'job_postings/refresh' => 'job_postings#refresh', as: :refresh_job_posting
  post 'job_postings/refresh' => 'job_postings#refresh_process', as: :refresh_job_posting_process
  get 'job_postings/:id' => 'job_postings#show', as: :job_posting
  get 'job_postings/:id/edit' => 'job_postings#edit', as: :edit_job_posting
  patch 'job_postings/:id' => 'job_postings#update'
  delete 'job_postings/:id' => 'job_postings#destroy'
  post 'job_postings' => 'job_postings#create'
  get 'job_postings/:id/compare' => 'job_postings#compare', as: :compare_applications

  get 'job_posting_applications/new' => 'job_posting_applications#new', as: :new_job_posting_application
  get 'job_posting_application/:id' => 'job_posting_applications#show', as: :job_posting_application
  post 'job_posting_applications' => 'job_posting_applications#create'
  patch 'job_posting_applications/:id' => 'job_posting_applications#update', as: :update_job_posting_application
  delete 'job_posting_application/:id' => 'job_posting_applications#destroy'

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/:id' => 'projects#show', as: :project
  get 'projects/:id/edit' => 'projects#edit', as: :edit_project
  patch 'projects/:id' => 'projects#update'
  post 'projects' => 'projects#create'
  delete 'projects/:id' => 'projects#destroy', as: :delete_project

  patch 'project_skills/:id' => 'project_skills#update'
  post 'project_skills' => 'project_skills#create'

  get 'references/refer' => 'references#email', as: :email_reference
  get 'references/new/:id' => 'references#new', as: :new_reference
  post 'references/refer' => 'references#send_mail', as: :reference_emails
  post 'references' => 'references#create'
  patch 'references/:id' => 'references#update', as: :update_reference
  delete 'references/:id' => 'references#destroy', as: :delete_reference

  delete 'reference_redirections/:id' => 'reference_redirections#destroy', as: :delete_reference_redirection

  get 'surveys/:title/compare' => 'surveys#compare', as: :compare_survey
  get 'surveys/:title/compare_to' => 'surveys#compare_to', as: :survey_compare_to
  get 'surveys/compare_all' => 'surveys#compare_all', as: :survey_compare_all
  get 'surveys' => 'surveys#index'
  get 'surveys/:title' => 'surveys#show', as: :survey
  get 'surveys/:title/edit' => 'surveys#edit', as: :edit_survey
  post 'responses' => 'responses#create'
  patch 'responses' => 'responses#update'

  get 'about_us' => 'welcome#about_us', as: :about_us
  get 'lost_email' => 'welcome#lost_email', as: :lost_email
  post 'lost_email' => 'welcome#send_lost_email', as: :send_lost_email
  get 'contact_us' => 'welcome#contact_us', as: :contact_us
  post 'contact_us' => 'welcome#send_contact_us', as: :send_contact_us
  root 'welcome#index'

  get '*path' => redirect('/')

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	has_many :questions
	accepts_nested_attributes_for :questions

	def format_title
		title_string = self.title
		# TODO: (Pseudo code)
		# If string contains digits
		# 	If string contains digits+st ||  digits+nd || digits+rd digits+th 
		# 		find the index following the digits
		# 		get substring following digits
		# 		make str = <sup> substring </sup>
		# 		insert  str into the string in place of digit suffix
		# 	end
		# end
		# return formatted title

		#in the mean time

		if title_string["21st Century Skills"]
			title_string = "21<sup>st</sup> Century Skills"
		end
		return title_string
	end

	def get_data(user, job_posting = '')
		if job_posting.blank?
			data = Response.find_by(user_id: user.id, survey_id: self.id)
		else
			data = Response.find_by(user_id: user.id, survey_id: self.id, job_posting_id: job_posting)
		end
		if(data)
			return data.get_data_map
		else
			return nil
		end
	end

	def get_average_data
		return Response.find_by(user_id: -1, survey_id: self.id).get_data_map
	end

	def self.get_title_map #Creates a hashmap of survey_id => "Survey title"
		rtn = Hash.new
		surveys = Survey.all
		surveys.each do |s|
			rtn[s.title ] = s.id
		end
		return rtn
	end

	def self.get_table_data(user, job_posting = '')
		surveys = Survey.all
		if job_posting.blank?
			responses = user.responses
		else
			responses = job_posting.responses
		end
		survey_results = Hash.new
		if !responses.empty?
			responses.each do |r| #performs 12 queries
				survey_results[r.survey_id] = r.get_data_map
			end
		end
		return survey_results
	end

	def self.get_average_data
		surveys = Survey.all
		survey_results = Hash.new
		Response.where("user_id = -1").find_each do |r|
			survey_results[r.survey_id] = r.get_data_map
		end
		return survey_results
	end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	include ConstantHelper

	before_action :authenticate_user!, except: [:show]
	before_action :check_role_jobseeker, only: [:compare_to, :compare_all]
	before_action :check_role_employer, only: [:compare]
	before_action :job_owner, only: [:compare]
	
	def show
		@survey = Survey.find_by(title: params[:title])
		if @survey.nil?
			flash[:warning] = "Sorry, we couldn't find that survey for that user."
			redirect_back_or and return
		end

		if params[:job_posting]
			@job_posting = JobPosting.find(params[:job_posting])
			@user = @job_posting.user
			name = @job_posting.title
			data = @survey.get_data(@user, @job_posting)
		elsif params[:user]
			@user = User.find(params[:user])
			if @user == current_user
				name = "Me"
			else
				name = @user.formatted_name(current_user)
			end
			data = @survey.get_data(@user)
		end
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end
		@survey_results = Array.new

		@survey_results.push(name: "Average Job Seeker", data: @survey.get_average_data)
		@survey_results.push(name: name, data: data)
		@questions = @survey.questions

		@prompts = Hash.new
		@questions.each do |q|
			@prompts = @prompts.merge({q.id => q.prompts})
		end
	end

	def edit
		@user = current_user
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end
		# Fetch Survey data
		if params[:job_posting]
			@job_posting = JobPosting.find(params[:job_posting])
			if @job_posting.user != current_user
				flash[:warning] = "You must own that job posting to edit the survey results."
				redirect_to current_user and return
			end
		elsif current_user.has_role? :employer
			flash[:warning] = "Sorry, job providers can only do surveys for job postings."
			redirect_to current_user and return
		end

		@survey = Survey.find_by(title: params[:title])
		if @survey.nil?
			flash[:warning] = "Sorry, we couldn't find that survey."
			redirect_to current_user and return
		end	

		if current_user.has_role? :employee
			@survey_results = @survey.get_data(current_user)
		elsif current_user.has_role? :employer
			@survey_results = @survey.get_data(current_user, params[:job_posting])
		else
			flash[:warning] = "Sorry, we couldn't find that survey."
			redirect_to current_user and return
		end
				
		@average_results = @survey.get_average_data
		@questions = @survey.questions
		@question_count = @questions.count
		@method = "post"
		@score_meanings = get_meanings(@survey.title)

		# Map the prompts to the questions
		@prompts = Hash.new
		@questions.each do |q|
			@prompts = @prompts.merge({q.id => q.prompts})
		end

		# Setup the Response variables
		@response = Response.new
		@values_array = Array.new(@question_count, 0)

		# Generates a collection array to remove labels
		@collection_array = Array.new()
		for i in 0..Integer(max_rating)
			@collection_array.push([i,''])
		end	
	
		# Load data if it exists
		if current_user.has_role? :employee
			@data = Response.find_by(user_id: current_user.id, survey_id: @survey.id)
		elsif current_user.has_role? :employer
			@data = Response.find_by(user_id: current_user.id, survey_id: @survey.id, job_posting_id: params[:job_posting])
		else
			flash[:warning] = "Sorry, we couldn't find that survey."
			redirect_to current_user and return
		end
		
		if @data != nil
			@method = "patch"
			@values_array = @data.scores
		end
	end

	def compare
		@user = current_user
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end

		@survey = Survey.find_by(title: params[:title])
		if @survey.nil?
			flash[:warning] = "Sorry, we couldn't find that survey."
			redirect_back_or and return
		end	

		@questions = @survey.questions
		@survey_results = Array.new

		@survey_results.push(name: "Average Job Seeker", data: @survey.get_average_data)
		@survey_results.push(name: "Ideal Candidate", data: @survey.get_data(@user, @job_posting))

		@job_posting_applications = @job_posting.job_posting_applications.where("status > ? ", -1)
		@job_posting_applications.each do |j|
			user_results = @survey.get_data(j.applicant)
			if user_results
				@survey_results.push(name: j.applicant.formatted_name(@job_posting.user_id), data: user_results)
			end
		end

		@prompts = Hash.new
		@questions.each do |q|
			@prompts = @prompts.merge({q.id => q.prompts})
		end
	end

	def compare_all
		if !params[:jp].blank?
			#compare to a job posting
			@survey_results = Array.new

			@job_posting = JobPosting.find(params[:jp])
			@user = @job_posting.user
			jp_results = Survey.get_table_data(@user, @job_posting)
			jp_results.each do |index, results|
				@survey_results[index] = Array.new if @survey_results[index].nil?
				@survey_results[index].push(name: @job_posting.title, data: results)
			end

			user_results = Survey.get_table_data(current_user)
			user_results.each do |index, results|
				@survey_results[index] = Array.new if @survey_results[index].nil?
				@survey_results[index].push(name: "Me", data: results)
			end
		elsif !params[:js].blank?
			#compare to another job seeker
			@survey_results = Array.new

			user_results = Survey.get_table_data(current_user)
			user_results.each do |index, results|
				@survey_results[index] = Array.new if @survey_results[index].nil?
				@survey_results[index].push(name: "Me", data: results)
			end

			@user = User.find(params[:js])
			user_results = Survey.get_table_data(@user)
			user_results.each do |index, results|
				@survey_results[index] = Array.new if @survey_results[index].nil?
				@survey_results[index].push(name: @user.formatted_name(current_user), data: results)
			end
		else
			#error
			flash[:warning] = "Sorry, there was an unexpected error.  Please try again or contact and administrator."
			redirect_to current_user
		end
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end
	end

	def compare_to

		@survey = Survey.find_by(title: params[:title])
		if @survey.nil?
			flash[:warning] = "Sorry, we couldn't find that survey."
			redirect_to current_user and return
		end

		@questions = @survey.questions
		@prompts = Hash.new
		@questions.each do |q|
			@prompts = @prompts.merge({q.id => q.prompts})
		end
		@survey_results = Array.new

		if !params[:jp].blank?
			#compare to a job posting
			@job_posting = JobPosting.find(params[:jp])
			@user = @job_posting.user

			if @job_posting.nil?
				flash[:warning] = "Sorry, we couldn't find that job posting."
				redirect_to current_user and return
			end

			@survey_results.push(name: @job_posting.title, data: @survey.get_data(@user, @job_posting.id))
			@survey_results.push(name: "Me", data: @survey.get_data(current_user)) unless current_user.has_role? :employer
		elsif !params[:js].blank?
			#compare to another job seeker
			@user = User.find(params[:js])

			if @user.nil? || @user.has_role?(:employer)
				flash[:warning] = "Sorry, we couldn't find that job seeker."
				redirect_to current_user and return
			end

			user_results = @survey.get_data(current_user)
			if user_results
				@survey_results.push(name: "Me", data: user_results)
			end

			user_results = @survey.get_data(@user)
			if user_results
				@survey_results.push(name: @user.formatted_name(current_user), data: user_results)
			end
		else
			#error
			flash[:warning] = "Sorry, there was an unexpected error.  Please try again or contact and administrator."
			redirect_to current_user
		end
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end
	end

private
	def check_role_jobseeker
		if !current_user.has_role? :employee
			redirect_to current_user, flash: {warning: "You need to be a job seeker or a potential job seeker to perform a survey."}
		end
	end

	def check_role_employer
		if !current_user.has_role? :employer
			redirect_to current_user, flash: {warning: "You need to be an employer to compare applicants."}
		end
	end

	def job_owner # Checks current user is the Job Posting owner
		@job_posting = JobPosting.find(params[:job_posting])
		if @job_posting.user_id != current_user.id
			flash[:danger] = 'You can only compare applicants on your own job posting.'
			redirect_back_or
		else
			return @job_posting
		end
	end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_display.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-8">
		<% if survey_results[0][:name]=="Average Job Seeker" %>
			<%= column_chart survey_results, min: 0, max: 3, library: { hAxis: {slantedText: true, slantedTextAngle: 30 }, legend: { position: "top" }, chartArea: {left: 50, width: '100%'}, series:{0 => {type: "line"}}, vAxis: { ticks: [{v: 0, f: "None"}, {v: 1, f: "Few"}, {v:2, f:"Half"}, {v: 3, f:"Most"}]}} %>
		<% else %>
			<%= column_chart survey_results, min: 0, max: 3, library: { hAxis: {slantedText: true, slantedTextAngle: 30 }, legend: { position: "top" }, chartArea: {left: 50, width: '100%'}, vAxis: { ticks: [{v: 0, f: "None"}, {v: 1, f: "Few"}, {v:2, f:"Half"}, {v: 3, f:"Most"}]}} %>
		<% end %>
	</div>
</div>
<br />

<% if survey_title == 'Time, Project, People' %>
	<p>There are 3 skill classifications: Time, Project, and People. Each classification has a list of skills associated with it.  Users rate themselves based on how well they know each group of skills: None of the skills, a few of the skills, half of the skills, or most/all of the skills.</p>
<% elsif survey_title == '21st Century Skills' %>
	<p>There are 4 skill classifications: Communication, Problem Solving, Self-Directed Skills, and Accountability. Each classification has a list of skills associated with it.  Users rate themselves based on how well they know each group of skills: None of the skills, a few of the skills, half of the skills, or most/all of the skills.</p>
<% else %>
	<p>There are 4 skill levels: Basic, Intermediate, Advanced, and Expert. Each level has a list of skills associated with it.  Users rate themselves based on how well they know each group of skills: None of the skills, a few of the skills, half of the skills, or most/all of the skills.</p>
<% end %>

<div class="row">
<% @questions.each_with_index do |question, index| %>
	<div class="col-xs-12 col-sm-6 col-md-3">
		<h4><b><%= question.classification %></b></h4>

		<ul>
			<% question.prompts.each do |p| %>
				<li class="alternate"><%= p.prompt %></li>
			<% end %>
		</ul>
	</div>
	<% if index%2 == 1 %>
		<div class = "clearfix visible-sm"></div>
	<% end %>
<% end %>

app/views/surveys/compare.html.erb
<%= render "users/shared/profile" %>

<%= render partial: "shared/site_tabs", locals: { active: 'applicants', job: @job_posting, posting_path: job_posting_path(@job_posting), user_path: user_path(@user) } %>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-6"><h2>Category: <%=@survey.format_title.html_safe%></h2> </div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-6"><br /><%= link_to 'Go back to comparing applicant graphs', compare_applications_path(@job_posting) %></div>
</div>

<%= render partial: "surveys/display", locals: { survey_results: @survey_results, survey_title: @survey.title } %>

app/views/surveys/compare_all.html.erb
<%= render "users/shared/profile" %>

<% if @user.has_role? :employee %>
	<%= render partial: "shared/site_tabs", locals: {active: "surveys", user_path: user_path(@user) } %>
<% elsif @user.has_role? :employer %>
	<%= render partial: "shared/site_tabs", locals: {active: "survey", survey: true, job: @job_posting, posting_path: job_posting_path(@job_posting), user_path: user_path(@user) } %>
<% end %>

<h4><b>Compare Skill Survey Graphs</b></h4>
<% if @user.has_role? :employee %>
	<p>Here you can quickly compare your skill graph with <%= @user.formatted_name(current_user)+"'s "%>.  If you want to see more info about each graph, click Details.</p>
<% elsif @user.has_role? :employer %>
	<p>Here you can view the 'ideal candidate' <%= @user.company_name %> is looking for.  If you want to see more info about each graph, click Details.</p>
<% end %>
<% i=1 %>
<div class="row">
	<% Survey.all.each do |s|%>
		<div class="compare-box col-xs-11 col-sm-5 col-md-5">
			<h5><%= s.format_title.html_safe %></h5>
			<%= column_chart @survey_results[i], min: 0, max: 3, library: { hAxis: {slantedText: true, slantedTextAngle: 30 }, legend: { position: "right" }, chartArea: {left: 40, width: '70%'}, vAxis: { ticks: [{v: 0, f: "None"}, {v: 1, f: "Few"}, {v:2, f:"Half"}, {v: 3, f:"Most"}]}} %>
			<% if @user.has_role? :employee %>
				<%= link_to "Details", survey_compare_to_path(s.title, js: params[:js]) %>
			<% elsif @user.has_role? :employer %>
				<%= link_to "Details", survey_compare_to_path(s.title, jp: params[:jp]) %>
			<% end %>
		</div>
		<% if i % 2 == 0 %>
			</div>
			<div class="row">
		<% end %>

		<% i = i+1 %>
	<% end %>
</div>

app/views/surveys/compare_to.html.erb
<%= render "users/shared/profile" %>

<% if @user.has_role? :employee %>
	<%= render partial: "shared/site_tabs", locals: {active: "surveys", user_path: user_path(@user) } %>
<% elsif @user.has_role? :employer %>
	<%= render partial: "shared/site_tabs", locals: {active: "survey", survey: true, job: @job_posting, posting_path: job_posting_path(@job_posting), user_path: user_path(@user) } %>
<% end %>

<h4><b>Category: <%=@survey.format_title.html_safe%></b></h4>

<%= render partial: "surveys/display", locals: { survey_results: @survey_results, survey_title: @survey.title } %>

app/views/surveys/edit.html.erb
<%= render "users/shared/profile" %>
<% if @user.has_role? :employee %>
	<%= render partial: "shared/site_tabs", locals: { active: 'survey', user_path: user_path(@user) } %>
<% elsif @user.has_role? :employer %>
	<%= render partial: "shared/site_tabs", locals: { active: 'survey', job: @job_posting, posting_path: job_posting_path(@job_posting), user_path: user_path(@user) } %>
<% end %>

<div class="row">
	<div class="col-md-6"> <h2>Category: <%=@survey.format_title.html_safe%></h2> </div>
</div>
<div class="row">
	<% if current_user.has_role? :employee %>
		<div class="col-md-6"><br /><%= link_to 'Go back to My Profile', user_path(current_user) %></div>
	<% end %>
</div>
<div class="row">
	<div class="col-md-6"></div>
	<div class="col-md-6">
	<% if current_user.has_role? :employee %>
		<% data_name = "Me" %>
	<% elsif current_user.has_role? :employer %>
		<% data_name = "Ideal Candidate" %>
	<% end %>
		<%= column_chart [
				{name: "Average Job Seeker", data: @average_results},
				{name: data_name, data: @survey_results}
				], height: "200px", min: 0, max: 3, library: { legend: { position: 'top' }, series:{0 => {type: "line"}}, vAxis: { ticks: [{v: 0, f: "None"}, {v: 1, f: "Few"}, {v:2, f:"Half"}, {v: 3, f:"Most"}]}} %>
	</div>
</div>
<div class="row row-style-top">
	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-style"></div>
		<% @score_meanings.each do |sm|%>
			<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 col-style"><%=sm%></div>
		<% end %>
</div>

<%= simple_form_for @response, method: @method do |f| %>
	<%= f.hidden_field :survey_id, value: @survey.id%>
	<%= f.hidden_field :job_posting_id, value: params[:job_posting] if current_user.has_role? :employer %>
	<% @initial_id = @questions.first.id %>
	<% for i in 0..@question_count-1 %>
		<div class="row row-style" >
			<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-style">
				<% @question = @questions.find_by(id: @initial_id + i) %>
				<h3> <%= @question.classification %> </h3>
				<ul>
					<% @question.prompts.each do |p| %>
						<li> <%= p.prompt %> </li>
					<% end %>
				</ul>
			</div>
											
			<%= f.input_field "scores[#{i}]",
			 	as: :radio_buttons,
			 	collection: @collection_array,
			 	label_method: :last, 
				value_method: :first, 
 				item_wrapper_class: 'col-xs-2 col-sm-2 col-md-2 col-lg-2 col-style margin-all-0',
 				item_label_class: 'center',
 				label: false,
 				checked: @values_array[i]
 			%>
			<%= f.hidden_field "question_ids[#{i}]", value: @question.id %>
		</div>
	<% end %>
	<%= f.button :submit, 'Submit', class: "btn btn-primary" %>
<% end %>

app/views/surveys/show.html.erb
<%= render "users/shared/profile" %>

<% if @user.has_role? :employee %>
	<%= render partial: "shared/site_tabs", locals: {active: "surveys", user_path: user_path(@user) } %>
<% elsif @user.has_role? :employer %>
	<%= render partial: "shared/site_tabs", locals: {active: "survey", survey: true, job: @job_posting } %>
<% end %>

<h4><b>Category: <%=@survey.format_title.html_safe%></b></h4>

<%= render partial: "surveys/display", locals: { survey_results: @survey_results, survey_title: @survey.title } %>