config/routes.rb
Rails.application.routes.draw do
  get 'settings/consent'

  get 'settings/privacy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Searchjoy::Engine, at: "/admin/searchjoy"
  get 'welcome/index'
  get 'signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'signup_employer' => 'welcome#signup_employer'
  get 'welcome/signup_jobseeker' => 'welcome#signup_jobseeker'
  get 'welcome/signup_employer' => 'welcome#signup_employer'

  get 'consent/business_consent/:id' => 'consent#business_consent', as: :business_consent
  get 'consent/adult_consent/:id' => 'consent#adult_consent', as: :adult_consent
  post 'consent/create' => 'consent#create'
  patch 'consent/update/:id' => 'consent#update'

  get 'search' => 'searches#index'
  get 'search/:id' => 'searches#navigate', as: :search_nav

  patch 'resource_links/all_announcements' => 'resource_links#update_all_announcements', as: :update_all_announcements
  patch 'resource_links/all_resource_links' => 'resource_links#update_all_resource_links', as: :update_all_resource_links

  get 'analytics' => 'analytics#index'
  get 'analytics/:id' => 'analytics#show', as: :analytics_report

  get 'notifications' => 'notifications#index'
  get 'notifications/show' => 'notifications#show', as: :show_notifications
  get 'notifications/:id' => 'notifications#trackable', as: :show_trackable
  patch 'notifications' => 'notifications#update'
  patch 'notifications/all' => 'notifications#update_all', as: :update_all_notifications
  delete 'notifications' => 'notifications#delete'
  delete 'notifications/all' => 'notifications#delete_all', as: :delete_all_notifications
  get 'users/referenceTab' => 'users#reference_tab'

  devise_for :users, controllers: { passwords: "users/passwords", sessions: "users/sessions", :registrations => "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  post 'users/home_tab' => 'users#home_tab'
  post 'users/nav_tab' => 'users#nav_tab'

  get '/users/:id/crop' => 'users#crop'
  get '/users/:id' => 'users#show', as: :user
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update'
  get 'users/:id/contact' => 'users#contact', as: :contact_user
  post 'users/:id/contact' => 'users#send_mail', as: :email_user

  patch 'skills/:id' => 'skills#update'
  post 'skills' => 'skills#create'
  get 'skills/autocomplete' => 'skills#autocomplete'

  get '/user_skills/:id/edit' => 'user_skills#edit', as: :edit_user_skill
  get '/user_skills/edit_all' => 'user_skills#edit_all', as: :edit_all_user_skill
  patch '/user_skills/update_all' => 'user_skills#update_all', as: :update_all_user_skill
  patch '/user_skills/:id' => 'user_skills#update'
  delete '/user_skills/:id' => 'user_skills#destroy', as: :delete_user_skill
  post '/user_skills' => 'user_skills#create'

  get 'job_postings' => 'job_postings#index'
  get 'job_postings/new' => 'job_postings#new', as: :new_job_posting
  get 'job_postings/refresh' => 'job_postings#refresh', as: :refresh_job_posting
  post 'job_postings/refresh' => 'job_postings#refresh_process', as: :refresh_job_posting_process
  get 'job_postings/:id' => 'job_postings#show', as: :job_posting
  get 'job_postings/:id/edit' => 'job_postings#edit', as: :edit_job_posting
  patch 'job_postings/:id' => 'job_postings#update'
  delete 'job_postings/:id' => 'job_postings#destroy'
  post 'job_postings' => 'job_postings#create'
  get 'job_postings/:id/compare' => 'job_postings#compare', as: :compare_applications

  get 'job_posting_applications/new' => 'job_posting_applications#new', as: :new_job_posting_application
  get 'job_posting_application/:id' => 'job_posting_applications#show', as: :job_posting_application
  post 'job_posting_applications' => 'job_posting_applications#create'
  patch 'job_posting_applications/:id' => 'job_posting_applications#update', as: :update_job_posting_application
  delete 'job_posting_application/:id' => 'job_posting_applications#destroy'

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/:id' => 'projects#show', as: :project
  get 'projects/:id/edit' => 'projects#edit', as: :edit_project
  patch 'projects/:id' => 'projects#update'
  post 'projects' => 'projects#create'
  delete 'projects/:id' => 'projects#destroy', as: :delete_project

  patch 'project_skills/:id' => 'project_skills#update'
  post 'project_skills' => 'project_skills#create'

  get 'references/refer' => 'references#email', as: :email_reference
  get 'references/new/:id' => 'references#new', as: :new_reference
  post 'references/refer' => 'references#send_mail', as: :reference_emails
  post 'references' => 'references#create'
  patch 'references/:id' => 'references#update', as: :update_reference
  delete 'references/:id' => 'references#destroy', as: :delete_reference

  delete 'reference_redirections/:id' => 'reference_redirections#destroy', as: :delete_reference_redirection

  get 'surveys/:title/compare' => 'surveys#compare', as: :compare_survey
  get 'surveys/:title/compare_to' => 'surveys#compare_to', as: :survey_compare_to
  get 'surveys/compare_all' => 'surveys#compare_all', as: :survey_compare_all
  get 'surveys' => 'surveys#index'
  get 'surveys/:title' => 'surveys#show', as: :survey
  get 'surveys/:title/edit' => 'surveys#edit', as: :edit_survey
  post 'responses' => 'responses#create'
  patch 'responses' => 'responses#update'

  get 'about_us' => 'welcome#about_us', as: :about_us
  get 'lost_email' => 'welcome#lost_email', as: :lost_email
  post 'lost_email' => 'welcome#send_lost_email', as: :send_lost_email
  get 'contact_us' => 'welcome#contact_us', as: :contact_us
  post 'contact_us' => 'welcome#send_contact_us', as: :send_contact_us
  root 'welcome#index'

  get '*path' => redirect('/')

end

app/models/reference.rb
class Reference < ActiveRecord::Base
	include PublicActivity::Model
	tracked only: :create, owner: ->(controller,model) {model && model.user}

	belongs_to :referee, :class_name => "User"
	belongs_to :user

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :company, presence: true
	validates :position, presence: true
	validates :reference_body, presence: true



	before_destroy :destroy_notification
private
	def destroy_notification
		PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: "Reference").destroy
	end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController

	before_action :authenticate_user!, except: [:new, :create]
	before_action :reference_owner, only: [:update, :destroy]
	before_action :check_email_fields, only: [:send_mail]

	def index # Shows a users unconfirmed, confirmed references and reference requests
		@confirmed_references = Reference.where(user_id: current_user.id, confirmed: true)
		@unconfirmed_references = Reference.where(user_id: current_user.id, confirmed: false)
		@reference_requests = ReferenceRedirection.where(email: current_user.email)
	end

	def show # Shows a specific reference
		@reference = Reference.find(params[:id])
	end

	def update # Confirms or Unconfirms a reference
		@reference.update(confirmed: !@reference.confirmed)
		msg = "Reference Confirmed!"
		unless @reference.confirmed
			msg = "Reference Unconfirmed!"
		end
		redirect_to current_user, flash: {info: msg}
	end

	def destroy # Deletes a reference
		@reference.destroy
		redirect_to current_user, flash: {info: "Reference deleted!"}
	end

	def email # Page for form to send an email
		@user = current_user
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end
		@url = ""
		loop do
			@url = SecureRandom.urlsafe_base64(10)
			break if ReferenceRedirection.where(reference_url: @url).empty?
		end
		@reference_email = ReferenceEmail.new 
	end

	def send_mail # Sends the email
		@reference_email = ReferenceEmail.new(reference_email_params)
		params[:reference_email][:user_id] = current_user.id
		reference_redirection = ReferenceRedirection.create(reference_email_params)
		referer = User.find_by(email: params[:reference_email][:email])
		unless referer.nil?
			reference_redirection.create_activity :request, owner: referer, parameters: {url: reference_redirection.reference_url}
		end

		ReferenceMailer.reference_email(@reference_email, current_user).deliver_now
		redirect_to current_user , flash: {success: "Reference request sent!"}
	end


	def new # Form to create a new reference
		@user = current_user
		if user_signed_in? && @user == current_user
			@user_buckets = user_bucket(4)
		end
		@reference_redirection = ReferenceRedirection.find_by(reference_url: params[:id])
		@reference_link = ReferenceRedirection.where(reference_url: params[:id])
		if !@reference_link.empty?
			@reference_link = @reference_link.first
			@referUser = User.find(@reference_link.user_id)
			@reference = Reference.new
		else
			redirect_to root_path , flash: {danger: "Invalid reference link"}
		end
	end

	def create # Post action which creates the reference
		if !request.referer.nil? && params[:url].blank?
			@url_string = request.referer.rpartition('/')[-1] # Retrieves the random part of the url on the new page
		elsif !params[:url].blank?
			@url_string = params[:url]
		end
		@reference_redirection = ReferenceRedirection.find_by(reference_url: @url_string)
		params[:url] = @url_string
		if !@reference_redirection.nil?
			@owner = false
			params[:reference][:user_id] = @reference_redirection.user_id
			@reference = Reference.new(reference_params)
			if user_signed_in?
				@reference.referee = current_user
				@owner = (@reference_redirection.user_id == current_user.id) # Stops a user from referencing themself
			end
			@verified = verify_recaptcha(model: @reference)
			if @verified && !@owner && @reference.save
				ReferenceRedirection.find_by(reference_url: @url_string).destroy # Removes the redirection url
				if user_signed_in?
					redirect_to current_user, flash: {success: "Thank you for making a reference!"}
				else
					redirect_to root_path , flash: {success: "Thank you for making a reference!"}
				end
			else
				if user_signed_in?
					@user = current_user
					if user_signed_in? && @user == current_user
						@user_buckets = user_bucket(4)
					end
				end
				@referUser = User.find(@reference_redirection.user_id)
				@reference_link = ReferenceRedirection.where(reference_url: params[:url]).first
				if !@verified
					flash[:warning] = "Please redo the Captcha"
				else
					flash[:warning] = "There was an issue in creating your reference"
				end
				@id = @url_string
				render 'new'
			end
		else
			flash[:danger] = "Invalid reference link"
			redirect_back_or root_path
		end
	end

private
	def reference_params # Restricts reference parameters
		params.require(:reference).permit(:first_name, :last_name, :company, :position, :reference_body, :user_id, :referee_id)
	end

	def reference_email_params # Restricts reference email parameters
		params.require(:reference_email).permit(:first_name, :last_name, :email, :reference_url, :user_id, :message)
	end

	def reference_owner # Checks if a user is the owner of a reference
		@reference = Reference.find(params[:id])
		if @reference.user_id != current_user.id
			flash[:danger] = 'Access denied as you are not owner of this Reference.'
			redirect_back_or current_user
		else
			return @reference
		end
	end

	def check_email_fields # Validate email parameters
		args = params[:reference_email]
		if args.nil?
			flash[:warning] = "Missing required fields"
		elsif args[:first_name].blank? || args[:last_name].blank? || args[:email].blank? || args[:message].blank?
			flash[:warning] = "Missing required fields"
		elsif args[:email] !~ Devise::email_regexp
			flash[:warning] =  "Enter a valid email address"
		elsif current_user.email == args[:email]
			flash[:warning] =  "You cannot give yourself a reference"
		end
		redirect_back_or email_reference_path if !flash[:warning].blank?
	end

	def check_reference_fields # Validate reference parameters
		args = params[:reference]
		if args.nil?
			flash[:warning] = "Missing required fields"
		elsif args[:first_name].blank? || args[:last_name].blank?|| args[:company].blank? || args[:position].blank? || args[:reference_body].blank?  
			flash[:warning] = "Missing required fields"
		end
		redirect_to new_reference_path(id: request.referer.rpartition('/')[-1], reference: params[:reference])if !flash[:warning].blank?
		#redirect_back_or new_reference_path(request.referer.rpartition('/')[-1]) if !flash[:warning].blank?
	end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/email.html.erb
<%= render "users/shared/profile" %>

<%= render partial: "shared/site_tabs", locals: {active: "references", user_path: user_path(@user) } %>

<div class ="container">
	<h4><b>Request a Reference</b></h4>
	<p> Fill out this form to ask your contact to give you a reference.</p><br />
		
	<%= simple_form_for @reference_email do |r| %>
		<div class="row">
			<%= r.input :first_name, required: true, wrapper_html: { class: "col-md-3" } %>
		</div>
		<div class="row">
			<%= r.input :last_name, required: true, wrapper_html: { class: "col-md-3" } %>
		</div>
		<div class="row">
			<%= r.input :email, as: "email", required: true, wrapper_html: { class: "col-md-3" } %>
		</div>
		<div class="row">
			<%= r.input :message, as: :text, required: true, wrapper_html: { class: "padding-left-15 col-md-3" } %>
		</div>
		<%= r.hidden_field :reference_url, :value => @url%>
		<%= r.button :submit, 'Send', class: "btn btn-primary" %>
	<% end %>
</div>

app/views/references/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %></div>
<% end %>

<div class="references">
	<div class="row">
		<% if @unconfirmed_references.empty? && @confirmed_references.empty? %>
			<h3>You have no references. <%= link_to "Click here to send a reference request!", email_reference_path %></h3>
		<% else %>
			<h3>Need more references? <%= link_to "Click here to send a reference request!", email_reference_path %></h3>
		<% end %>
		<br>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<h3> Confirmed References </h3>
			<% if !@confirmed_references.empty? %>
				<% @confirmed_references.each do |r| %>
<div id="ref">
						<div id="left">
							<img src="https://image.freepik.com/free-icon/user-male-silhouette_318-55563.png" class="refLeft" id="refImage"/>
							<p class="refLeft" id="refName"><%= r.first_name%> <%= r.last_name %></p>
							<h4 class="refLeft"><%= r.position %></h4>
							<h4 class="refLeft"><%= r.company%></h4>
							<h5 class="refLeft"><%= link_to "Unconfirm", update_reference_path(r), method: "patch", class: "btn btn-warning" %> <%= link_to "Delete", delete_reference_path(r), method: "delete", data: {confirm: "Are you sure you want to delete this reference?"}, class: "btn btn-danger" %></h5>
						</div>
						<div id="centre">
							<p class="refCentre" id="refContent"><%= r.reference_body %></p>
						</div>
						<div id="right">
							<div id="relEmployment">
								<label for="sel1">Relevant Employment:</label>
      								<select class="form-control" id="sel1">
									<option value='Employer 1'>Employer 1</option>
								</select>
							</div>
							<div id="relProjects">
								<label for="sel2">Relevant Projects:</label>
      								<select class="form-control" id="sel2">
									<option value='Project 1'>Project 1</option>
								</select>

							</div>
							<div id="contact">
								<h6 class="refLeft"><b>Contact:</b></h6>
								<h6 class="refLeft contactElm">Email: <%= r.email %></h6>
								<% if r.phone_number.empty? %>
								<% puts %> 
								<% else %>
								<h6 class="refLeft contactElm">Phone: <%= r.phone_number %> </h6>
								<% end %>
							</div>
						</div>
			
					</div>
					<hr class="HR"/>
				<% end %>
			<% else %>
				<h6> You have no confirmed references.
			<% end %>
		</div>
		<div class="col-xs-12">
			<h3> Unconfirmed References </h3>&nbsp;
			<% if !@unconfirmed_references.empty? %>
				<% @unconfirmed_references.each do |r| %>
					<div id="ref2">
						<div id="left2">
							<img src="https://image.freepik.com/free-icon/user-male-silhouette_318-55563.png" class="refLeft" id="refImage2"/>
							<p class="refLeft" id="refName2"><%= r.first_name%> <%= r.last_name %></p>
							<h4 class="refLeft"><%= r.position %></h4>
							<h4 class="refLeft"><%= r.company%></h4>
							<h5 class="refLeft"><%= link_to "Confirm", update_reference_path(r), method: "patch", class: "btn btn-success" %> <%= link_to "Delete", delete_reference_path(r), method: "delete", data: {confirm: "Are you sure you want to delete this reference?"}, class: "btn btn-danger" %></h5>
						</div>
						<div id="centre2">
							<p class="refCentre" id="refContent"><%= r.reference_body %></p>
						</div>
						<div id="right">
							<div id="relEmployment2">
								<label for="sel1">Relevant Employment:</label>
      								<select class="form-control" id="sel1">
									<option value='Employer 1'>Employer 1</option>
								</select>
							</div>
							<div id="relProjects2">
								<label for="sel2">Relevant Projects:</label>
									<select class="form-control" id="sel2">
										<option value='project1'>project1</option>
									</select>
								<%# @projects.each do |p| %>
      									<!--<select class="form-control" id="sel2">
										<option value='<%# p.title %>'><%# p.title %></option>
									</select>-->
								<%# end %>
							</div>
							<div id="contact2">
								<h6 class="refLeft"><b>Contact:</b></h6>
								<h6 class="refLeft contactElm">Email: <%= r.email %></h6>
								<% if r.phone_number.empty? %>
								<% puts %> 
								<% else %>
								<h6 class="refLeft contactElm">Phone: <%= r.phone_number %> </h6>
								<% end %>
							</div>
						</div>
			
					</div>
					<hr class="HR"/>
				<% end %>
			<% else %>
				<h6> You have no unconfirmed references. </h6>
			<% end %>
		</div>

		<div class="col-xs-6">
			<h3> References Requests </h3>
			<% if !@reference_requests.empty? %>
				<% @reference_requests.each do |r| %>
					<h4><%= link_to "#{r.user.first_name} #{r.user.last_name}", user_path(r.user_id) %> <%= link_to "Refer", new_reference_path(r.reference_url)%></h4>
				<% end %>
			<% else %>
				<h6> You have no reference requests. </h6>
			<% end %>
		</div>
	</div>
</div>

app/views/references/new.html.erb
<% if user_signed_in? %>
	<%= render "users/shared/profile" %>
	<%= render partial: "shared/site_tabs", locals: {active: "references", user_path: user_path(@user) } %>
<% else %>
	<div class="padding-15 row">
		<div class="learn-more col-md-12">
			<h3 class="learn-text">Want to learn more about EdgeMap and what it has to offer?  Check us out <%= link_to 'here', welcome_index_path, style:"color:white;" %></h3>
		</div>
	</div>
<% end %>

<div class ="padding-30 row">
	<div class="col-md-2">
		<%= image_tag @referUser.image(:small), alt:"User Icon", class: "profile-image small-shadow" %>
	</div>
	<div class="col-md-3">
		<div class="row">
			<h5><%= @referUser.first_name%> <%= @referUser.last_name %></h5>
		</div>
	</div>
	<div class="col-md-4">
		<div class="row">
			<h5>Message:</h5>
			<h5><%= @reference_redirection.message %></h5>
		</div>
	</div>
	<div class="col-md-3">
		<div style="float:right;">
			<%= link_to "View", user_path(@referUser), class: "btn btn-primary"%>
			<%= link_to "Delete", delete_reference_redirection_path(@reference_redirection), method: :delete, data: {confirm: "Are you sure you want to delete this request?"}, class: "btn btn-danger" %>
		</div>
	</div>
</div>

<h4>Your Reference</h4>
<p>
	You are giving a reference to <%= @referUser.first_name %> <%= @referUser.last_name %>.  Please fill out the form below, and thank you for your time.
	<% if user_signed_in? %>
		By completing this reference, you allow other users to see your name and picture on <%= @referUser.first_name %> <%= @referUser.last_name %>'s profile.  If you have set your security settings otherwise, your info will still be unavailable in other places, but visible on <%= @referUser.first_name %> <%= @referUser.last_name %>'s profile.
	<% end %>
</p>
	<%if !user_signed_in?%>
	<p><% if User.find_by(email: @reference_link.email.downcase) != nil%>
			Hey we can see you have a <%=ENV['HOST_NAME']%> account<br>
			Please <%= link_to "sign in", new_user_session_path %> and then fill in this form
		<% else %>
			If you have a <%=ENV['HOST_NAME']%> account please <%= link_to "sign in", new_user_session_path %> and then fill in this form
		<% end %>
	</p>
	<% end %>
<%= simple_form_for @reference do |r| %>
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<%= r.input :first_name, required: true, input_html: {value: @reference.first_name ? @reference.first_name : @reference_link.first_name }%>
		</div>
		<div class="col-md-6 col-sm-6">
			<%= r.input :company, required: true, input_html: {value: @reference.company ? @reference.company : '' } %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<%= r.input :last_name, input_html: {value: @reference.last_name ? @reference.last_name : @reference_link.last_name } %>
		</div>
		<div class="col-md-6 col-sm-6">
			<%= r.input :position, required: true, input_html: {value: @reference.position ? @reference.position : '' } %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<%= r.input :reference_body, required: true, wrapper_html: { class: 'padding-left-0' }, input_html: { value: @reference.reference_body ? @reference.reference_body : ''} %>
		</div>
	</div>
	<% if @id %>
		<%= hidden_field_tag(:url, @id) %>
	<% end %>
	<%= recaptcha_tags %><br>
	<%= r.button :submit, class: "btn btn-primary" %>
<% end -%>

app/views/references/show.html.erb
<%= link_to "References", references_path %>
<% r = @reference %>
<h3><%= r.first_name%> <%= r.last_name %></h3>
<h4><%= r.company%>: <%= r.position %></h4>
<h6>Contact: Email: <%= r.email %>, Phone: <%= r.phone_number %></h6>
<p><%= r.reference_body %></p>
<% if @reference.confirmed%>
	<%= link_to "Unconfirm", update_reference_path(r), method: "patch", class: "btn btn-warning" %> <%= link_to "Delete", delete_reference_path(r), data: {confirm: "Are you sure you want to delete this reference?"}, method: "delete", class: "btn btn-danger" %>
<% else %>
	<%= link_to "Confirm", update_reference_path(r), method: "patch", class: "btn btn-success" %> <%= link_to "Delete", delete_reference_path(r), data: {confirm: "Are you sure you want to delete this reference?"}, method: "delete", class: "btn btn-danger" %> 
<% end %>